# Generated by Django 4.2 on 2023-05-04 20:04

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('userFoto', models.FileField(blank=True, null=True, upload_to='fotos/')),
                ('userTipo', models.CharField(choices=[('Instructor', 'Instructor'), ('Aprendiz', 'Aprendiz'), ('Administrativo', 'Administrativo')], max_length=15)),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True)),
                ('FechaHoraActualizacion', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleSolicuitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detCantidadRequerida', models.IntegerField()),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True)),
                ('FechaHoraActualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eleCodigo', models.CharField(max_length=15, unique=True)),
                ('eleNombre', models.CharField(max_length=50)),
                ('eleTipo', models.CharField(choices=[('Herramientas', 'Herramientas'), ('Maquinaria', 'Maquinaria'), ('Equipos', 'Equipos'), ('Materiales', 'Materiales')], max_length=12)),
                ('eleEstado', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo')], max_length=50)),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True)),
                ('FechaHoraActualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estNombre', models.CharField(choices=[('Satisfactorio', 'Satisfactorio'), ('Requiere Ajuste', 'Requiere Ajuste'), ('Requiere Reparacion', 'Requiere Reparacion'), ('Requiere Reemplazo', 'Requiere Reemplazo'), ('Defecto Corregido', 'Defecto Corregido')], max_length=50, unique=True)),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True)),
                ('FechaHoraActualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficCodigo', models.IntegerField(db_comment='Codigo de la Ficha', unique=True)),
                ('ficNombre', models.CharField(max_length=100)),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True)),
                ('FechaHoraActualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proTipo', models.CharField(choices=[('Persona Juridica', 'Persona Juridica'), ('Persona Natural', 'Persona Natural')], max_length=16)),
                ('proIdentificacion', models.CharField(max_length=45, unique=True)),
                ('proNombre', models.CharField(max_length=45)),
                ('proRepresentanteLegal', models.CharField(max_length=60, null=True)),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True)),
                ('FechaHoraActualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniNombre', models.CharField(max_length=45, unique=True)),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True)),
                ('FechaHoraActualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UbicacionFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubiDeposito', models.IntegerField()),
                ('ubiEstante', models.IntegerField(null=True)),
                ('ubiEntrepano', models.IntegerField(null=True)),
                ('ubiLocker', models.SmallIntegerField()),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True)),
                ('FechaHoraActualizacion', models.DateTimeField(auto_now=True)),
                ('ubiElemento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appGestionInv.elemento')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solProyecto', models.CharField(max_length=500)),
                ('solFechaHoraRequerida', models.DateTimeField(null=True)),
                ('solEstado', models.CharField(choices=[('Solicitada', 'Solicitada'), ('Aprobada', 'Aprobada'), ('Atendida', 'Atendida'), ('Cancelada', 'Cancelada')], max_length=10)),
                ('solObservaciones', models.TextField(null=True)),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True)),
                ('FechaHoraActualizacion', models.DateTimeField(auto_now=True)),
                ('solFicha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appGestionInv.ficha')),
                ('solUsuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalidaDetalleSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salCantidadEntregada', models.IntegerField()),
                ('salObservaciones', models.TextField(null=True)),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True)),
                ('FechaHoraActualizacion', models.DateTimeField(auto_now=True)),
                ('salDetalleSolicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appGestionInv.detallesolicuitud')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matReferencia', models.TextField(null=True)),
                ('matMarca', models.CharField(max_length=50, null=True)),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True)),
                ('FechaHoraActualizacion', models.DateTimeField(auto_now=True)),
                ('matElemento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appGestionInv.elemento')),
                ('matUnidadMedida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appGestionInv.unidadmedida')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manObservaciones', models.TextField(null=True)),
                ('manFechaHoraMantenimiento', models.DateTimeField()),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True)),
                ('FechaHoraActualizacion', models.DateTimeField(auto_now=True)),
                ('manElemento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appGestionInv.elemento')),
                ('manEstado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appGestionInv.estadomantenimiento')),
                ('manPersona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntradaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entNumeroFactura', models.CharField(max_length=15)),
                ('entFechaHora', models.DateTimeField(default=datetime.datetime(2023, 5, 4, 15, 4, 48, 103441))),
                ('entEntregadoPor', models.CharField(max_length=100)),
                ('entObservaciones', models.TextField(null=True)),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True)),
                ('FechaHoraActualizacion', models.DateTimeField(auto_now=True)),
                ('entProveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appGestionInv.proveedor')),
                ('entUsuarioRecibe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Devolutivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devPlacaSena', models.CharField(max_length=50, null=True)),
                ('devSerial', models.CharField(max_length=50, null=True)),
                ('devDescripcion', models.TextField()),
                ('devMarca', models.CharField(max_length=50, null=True)),
                ('devFechaIngresoSena', models.DateField()),
                ('devValor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('devFoto', models.FileField(blank=True, null=True, upload_to='elementos/')),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True)),
                ('FechaHoraActualizacion', models.DateTimeField(auto_now=True)),
                ('devElemento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appGestionInv.elemento')),
            ],
        ),
        migrations.CreateModel(
            name='DevolucionElemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devCantidadDevoluicion', models.IntegerField()),
                ('devObservaciones', models.TextField(null=True)),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True)),
                ('FechaHoraActualizacion', models.DateTimeField(auto_now=True)),
                ('devSalida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appGestionInv.salidadetallesolicitud')),
                ('devUsuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='detallesolicuitud',
            name='detElemento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appGestionInv.elemento'),
        ),
        migrations.AddField(
            model_name='detallesolicuitud',
            name='detSolicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appGestionInv.solicitudelemento'),
        ),
        migrations.AddField(
            model_name='detallesolicuitud',
            name='detUnidadMedida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appGestionInv.unidadmedida'),
        ),
        migrations.CreateModel(
            name='DetalleEntradaMateriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detCantidad', models.IntegerField()),
                ('detPrecioUnitario', models.FloatField()),
                ('detEstado', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo')], max_length=7)),
                ('fechaHoraCreacion', models.DateTimeField(auto_now_add=True)),
                ('FechaHoraActualizacion', models.DateTimeField(auto_now=True)),
                ('detEntradaMaterial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appGestionInv.entradamaterial')),
                ('detMaterial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appGestionInv.material')),
            ],
        ),
    ]
